version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["nodejs"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Frigyes06/aether-app"

[[transformers]]
name = "prettier"