name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 2
      uses: actions/setup-python@v4
      with:
        python-version: '2.x'
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.15'
        
    - name: Use Node.js 16.18
      uses: actions/setup-node@v3
      with:
        node-version: '11'
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
        
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true

    - name: test backend
      working-directory: aether-core/aether/backend
      run: go run main.go

    - name: Build the frontend
      working-directory: aether-core/aether/client
      run: npm ci; npm run wpbuild; npm run rebuild

    - name: Install dependencies
      working-directory: aether-core/aether
      run: make

    - name: Build linux
      working-directory: aether-core/aether
      run: make linux

    - name: Build windows
      working-directory: aether-core/aether
      run: make win
      
    - name: Build mac
      working-directory: aether-core/aether
      run: make mac
      
    - name: Test
      working-directory: aether-core/aether
      run: bash run-test.sh
